
on:
  pull_request:
    branches:
    - main
jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: |
        dotnet build BookmarkGen
        dotnet build BookmarkGenConsole