on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+' # see: semver.org

jobs:
  publish-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Validate Builds
      run: |
        dotnet build BookmarkGen -c Release
        dotnet build BookmarkGenConsole -c Release
    - name: Test
      run: |
        dotnet test BookmarkGen.Tests
    - name: Publish Binary
      run: |
        dotnet publish BookmarkGenConsole -c Release -o out --self-contained -r linux-x64
        mv out/BookmarkGenConsole out/gitmarker-linux
        dotnet publish BookmarkGenConsole -c Release -o out --self-contained -r win-x64
        mv out/BookmarkGenConsole.exe out/gitmarker-win.exe
        dotnet publish BookmarkGenConsole -c Release -o out --self-contained -r osx-x64
        mv out/BookmarkGenConsole out/gitmarker-darwin
    - name: Create Release
      uses: softprops/action-gh-release@v1
     
      with:
        draft: true
        body: 'Console release of Bookmark Gen'
        files: |
          out/gitmarker-linux
          out/gitmarker-win.exe
          out/gitmarker-darwin