on:
  push:
    #tags:
    #- 'v[0-9]+.[0-9]+.[0-9]+' # see: semver.org

jobs:
  publish-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Validate Builds
      run: |
        dotnet build BookmarkGen -c Release
        dotnet build BookmarkGenConsole -c Release
    - name: Test
      run: |
        dotnet test BookmarkGen.Tests
    - name: Publish Binary
      run: |
        dotnet publish BookmarkGenConsole -c Release
